modLoader="javafml"
loaderVersion="[34,)"
license="MIT"
issueTrackerURL="https://github.com/ochotonida/festive-creepers/issues"

[[mods]]
modId="festive_creepers"
version="1.16.4-1.1.0"
displayName="Festive Creepers"

displayURL="https://www.curseforge.com/minecraft/mc-mods/festive-creepers"
logoFile="logo.png"
authors="ochotonida"
description='''
Adds festive creepers and fireworks crates
'''

[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"
